In [1]:
name <- "Lavanya"
age <- 21
marks <- 90

print(name)
print(age)
print(marks)

[1] "Lavanya"
[1] 21
[1] 90

In [2]:
cat("Name:",name)
cat("Age:",age)

paste("Student Name is", name)

Name: LavanyaAge: 21

[1] "Student Name is Lavanya"

In [3]:
x <- c(20,40,60,80,100)

print(x)
length(x)
sum(x)
mean(x)
min(x)
max(x)

[1]  20  40  60  80 100

[1] 5

[1] 300

[1] 60

[1] 20

[1] 100

In [4]:
s <- matrix(c(1:20), nrow=2, ncol=10)

s

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    3    5    7     9   11   13   15   17   19
[2,] 2    4    6    8    10   12   14   16   18   20

In [5]:
s[1,3]
s[2,5]
s[,3]
s[1,]

[1] 5

[1] 10

[1] 5 6

 [1]  1  3  5  7  9 11 13 15 17 19

In [6]:
nrow(s)
ncol(s)
dim(s)

[1] 2

[1] 10

[1]  2 10

In [7]:
data <- data.frame(
  RollNo = c(101,102,103,104,105),
  Name = c("Goki","Thirisha","Narmatha","Subi","Kowsi"),
  Age = c(21,22,20,23,21),
  Marks = c(90,89,90,85,75)
)

data

  RollNo Name     Age Marks
1 101    Goki     21  90
2 102    Thirisha 22  89
3 103    Narmatha 20  90
4 104    Subi     23  85
5 105    Kowsi    21  75

In [8]:
head(data)
tail(data)

  RollNo Name     Age Marks
1 101    Goki     21  90
2 102    Thirisha 22  89
3 103    Narmatha 20  90
4 104    Subi     23  85
5 105    Kowsi    21  75

  RollNo Name     Age Marks
1 101    Goki     21  90
2 102    Thirisha 22  89
3 103    Narmatha 20  90
4 104    Subi     23  85
5 105    Kowsi    21  75

In [9]:
nrow(data)
ncol(data)
dim(data)

[1] 5

[1] 4

[1] 5 4

In [10]:
colnames(data)
rownames(data)

summary(data)

[1] "RollNo" "Name"   "Age"    "Marks"

[1] "1" "2" "3" "4" "5"

     RollNo           Name        Age           Marks
 Min.   :101   Length   :5   Min.   :20.0   Min.   :75.0
 1st Qu.:102   N.unique :5   1st Qu.:21.0   1st Qu.:85.0
 Median :103   N.blank  :0   Median :21.0   Median :89.0
 Mean   :103   Min.nchar:4   Mean   :21.4   Mean   :85.8
 3rd Qu.:104   Max.nchar:8   3rd Qu.:22.0   3rd Qu.:90.0
 Max.   :105                 Max.   :23.0   Max.   :90.0

In [13]:
data[1,]      # First row
data[2,3]     # 2nd row, 3rd column
data$Marks    # Marks column
data$Name     # Name column

  RollNo Name Age Marks
1 101    Goki 21  90

[1] 22

[1] 90 89 90 85 75

[1] "Goki"     "Thirisha" "Narmatha" "Subi"     "Kowsi"

In [14]:
mean(data$Marks)
min(data$Marks)
max(data$Marks)

[1] 85.8

[1] 75

[1] 90

In [2]:

employee<- read.csv("Salary Data.csv")

head(employee)
tail(employee)

summary(employee)

colnames(employee)
rownames(employee)

nrow(employee)
ncol(employee)

  Age Gender Education.Level Job.Title         Years.of.Experience Salary
1 32  Male   Bachelor's      Software Engineer  5                   90000
2 28  Female Master's        Data Analyst       3                   65000
3 45  Male   PhD             Senior Manager    15                  150000
4 36  Female Bachelor's      Sales Associate    7                   60000
5 52  Male   Master's        Director          20                  200000
6 29  Male   Bachelor's      Marketing Analyst  2                   55000

    Age Gender Education.Level Job.Title
370 33  Male   Bachelor's      Junior Business Analyst
371 35  Female Bachelor's      Senior Marketing Analyst
372 43  Male   Master's        Director of Operations
373 29  Female Bachelor's      Junior Project Manager
374 34  Male   Bachelor's      Senior Operations Coordinator
375 44  Female PhD             Senior Business Analyst
    Years.of.Experience Salary
370  4                   60000
371  8                   85000
372 19                  170000
373  2                   40000
374  7                   90000
375 15                  150000

      Age              Gender     Education.Level     Job.Title
 Min.   :23.00   Length   :375   Length   :375    Length   :375
 1st Qu.:31.00   N.unique :  2   N.unique :  3    N.unique :174
 Median :36.00   N.blank  :  0   N.blank  :  0    N.blank  :  0
 Mean   :37.43   Min.nchar:  4   Min.nchar:  3    Min.nchar:  3
 3rd Qu.:44.00   Max.nchar:  6   Max.nchar: 10    Max.nchar: 37
 Max.   :53.00
 NAs    :2
 Years.of.Experience     Salary
 Min.   : 0.00       Min.   :   350
 1st Qu.: 4.00       1st Qu.: 55000
 Median : 9.00       Median : 95000
 Mean   :10.03       Mean   :100577
 3rd Qu.:15.00       3rd Qu.:140000
 Max.   :25.00       Max.   :250000
 NAs    :2           NAs    :2

[1] "Age"                 "Gender"              "Education.Level"
[4] "Job.Title"           "Years.of.Experience" "Salary"

  [1] "1"   "2"   "3"   "4"   "5"   "6"   "7"   "8"   "9"   "10"  "11"  "12"
 [13] "13"  "14"  "15"  "16"  "17"  "18"  "19"  "20"  "21"  "22"  "23"  "24"
 [25] "25"  "26"  "27"  "28"  "29"  "30"  "31"  "32"  "33"  "34"  "35"  "36"
 [37] "37"  "38"  "39"  "40"  "41"  "42"  "43"  "44"  "45"  "46"  "47"  "48"
 [49] "49"  "50"  "51"  "52"  "53"  "54"  "55"  "56"  "57"  "58"  "59"  "60"
 [61] "61"  "62"  "63"  "64"  "65"  "66"  "67"  "68"  "69"  "70"  "71"  "72"
 [73] "73"  "74"  "75"  "76"  "77"  "78"  "79"  "80"  "81"  "82"  "83"  "84"
 [85] "85"  "86"  "87"  "88"  "89"  "90"  "91"  "92"  "93"  "94"  "95"  "96"
 [97] "97"  "98"  "99"  "100" "101" "102" "103" "104" "105" "106" "107" "108"
[109] "109" "110" "111" "112" "113" "114" "115" "116" "117" "118" "119" "120"
[121] "121" "122" "123" "124" "125" "126" "127" "128" "129" "130" "131" "132"
[133] "133" "134" "135" "136" "137" "138" "139" "140" "141" "142" "143" "144"
[145] "145" "146" "147" "148" "149" "150" "151" "152" "153" "154" "155" "156"
[157] "157" "158" "159" "160" "161" "162" "163" "164" "165" "166" "167" "168"
[169] "169" "170" "171" "172" "173" "174" "175" "176" "177" "178" "179" "180"
[181] "181" "182" "183" "184" "185" "186" "187" "188" "189" "190" "191" "192"
[193] "193" "194" "195" "196" "197" "198" "199" "200" "201" "202" "203" "204"
[205] "205" "206" "207" "208" "209" "210" "211" "212" "213" "214" "215" "216"
[217] "217" "218" "219" "220" "221" "222" "223" "224" "225" "226" "227" "228"
[229] "229" "230" "231" "232" "233" "234" "235" "236" "237" "238" "239" "240"
[241] "241" "242" "243" "244" "245" "246" "247" "248" "249" "250" "251" "252"
[253] "253" "254" "255" "256" "257" "258" "259" "260" "261" "262" "263" "264"
[265] "265" "266" "267" "268" "269" "270" "271" "272" "273" "274" "275" "276"
[277] "277" "278" "279" "280" "281" "282" "283" "284" "285" "286" "287" "288"
[289] "289" "290" "291" "292" "293" "294" "295" "296" "297" "298" "299" "300"
[301] "301" "302" "303" "304" "305" "306" "307" "308" "309" "310" "311" "312"
[313] "313" "314" "315" "316" "317" "318" "319" "320" "321" "322" "323" "324"
[325] "325" "326" "327" "328" "329" "330" "331" "332" "333" "334" "335" "336"
[337] "337" "338" "339" "340" "341" "342" "343" "344" "345" "346" "347" "348"
[349] "349" "350" "351" "352" "353" "354" "355" "356" "357" "358" "359" "360"
[361] "361" "362" "363" "364" "365" "366" "367" "368" "369" "370" "371" "372"
[373] "373" "374" "375"

[1] 375

[1] 6

In [3]:
s <- matrix(c(1:20), nrow=2, ncol=10)

s
s[1,3]
s[2,5]
s[,3]
s[1,]

nrow(s)
ncol(s)
dim(s)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    3    5    7     9   11   13   15   17   19
[2,] 2    4    6    8    10   12   14   16   18   20

[1] 5

[1] 10

[1] 5 6

 [1]  1  3  5  7  9 11 13 15 17 19

[1] 2

[1] 10

[1]  2 10

In [4]:

employee

head(employee)

tail(employee)

str(employee)

summary(employee)

nrow(employee)

ncol(employee)

dim(employee)

colnames(employee)

rownames(employee)

names(employee)

    Age Gender Education.Level Job.Title
1   32  Male   Bachelor's      Software Engineer
2   28  Female Master's        Data Analyst
3   45  Male   PhD             Senior Manager
4   36  Female Bachelor's      Sales Associate
5   52  Male   Master's        Director
6   29  Male   Bachelor's      Marketing Analyst
7   42  Female Master's        Product Manager
8   31  Male   Bachelor's      Sales Manager
9   26  Female Bachelor's      Marketing Coordinator
10  38  Male   PhD             Senior Scientist
11  29  Male   Master's        Software Developer
12  48  Female Bachelor's      HR Manager
13  35  Male   Bachelor's      Financial Analyst
14  40  Female Master's        Project Manager
15  27  Male   Bachelor's      Customer Service Rep
16  44  Male   Bachelor's      Operations Manager
17  33  Female Master's        Marketing Manager
18  39  Male   PhD             Senior Engineer
19  25  Female Bachelor's      Data Entry Clerk
20  51  Male   Bachelor's      Sales Director
21  34  Female Master's        Business Analyst
22  47  Male   Master's        VP of Operations
23  30  Male   Bachelor's      IT Support
24  36  Female Bachelor's      Recruiter
25  41  Male   Master's        Financial Manager
26  28  Female Bachelor's      Social Media Specialist
27  37  Female Master's        Software Manager
28  24  Male   Bachelor's      Junior Developer
29  43  Female PhD             Senior Consultant
30  33  Male   Master's        Product Designer
⋮   ⋮   ⋮      ⋮               ⋮
346 33  Male   Bachelor's      Junior Business Analyst
347 35  Female Bachelor's      Senior Marketing Analyst
348 45  Male   Master's        Director of Engineering
349 28  Female Bachelor's      Junior Operations Manager
350 36  Male   Bachelor's      Senior Business Development Manager
351 44  Female PhD             Senior Data Scientist
352 31  Male   Bachelor's      Junior Marketing Coordinator
353 38  Female Bachelor's      Senior Business Analyst
354 48  Male   Master's        Director of Marketing
355 31  Female Bachelor's      Junior Business Development Associate
356 40  Male   Bachelor's      Senior Financial Analyst
357 45  Female PhD             Senior UX Designer
358 33  Male   Bachelor's      Junior Product Manager
359 36  Female Bachelor's      Senior Marketing Manager
360 47  Male   Master's        Director of Operations
361 29  Female Bachelor's      Junior Project Manager
362 34  Male   Bachelor's      Senior Operations Coordinator
363 44  Female PhD             Senior Business Analyst
364 33  Male   Bachelor's      Junior Marketing Specialist
365 35  Female Bachelor's      Senior Financial Manager
366 43  Male   Master's        Director of Marketing
367 31  Female Bachelor's      Junior Financial Analyst
368 41  Male   Bachelor's      Senior Product Manager
369 44  Female PhD             Senior Data Engineer
370 33  Male   Bachelor's      Junior Business Analyst
371 35  Female Bachelor's      Senior Marketing Analyst
372 43  Male   Master's        Director of Operations
373 29  Female Bachelor's      Junior Project Manager
374 34  Male   Bachelor's      Senior Operations Coordinator
375 44  Female PhD             Senior Business Analyst
    Years.of.Experience Salary
1    5                   90000
2    3                   65000
3   15                  150000
4    7                   60000
5   20                  200000
6    2                   55000
7   12                  120000
8    4                   80000
9    1                   45000
10  10                  110000
11   3                   75000
12  18                  140000
13   6                   65000
14  14                  130000
15   2                   40000
16  16                  125000
17   7                   90000
18  12                  115000
19   0                   35000
20  22                  180000
21   5                   80000
22  19                  190000
23   2                   50000
24   9                   60000
25  13                  140000
26   3                   45000
27  11                  110000
28   1                   40000
29  15                  140000
30   6                   90000
⋮   ⋮                   ⋮
346  4                   60000
347  8                   85000
348 19                  180000
349  1                   35000
350  8                  110000
351 16                  160000
352  3                   55000
353 10                  110000
354 21                  180000
355  3                   50000
356 12                  130000
357 16                  160000
358  4                   60000
359  8                   95000
360 19                  170000
361  2                   40000
362  7                   90000
363 15                  150000
364  5                   70000
365  8                   90000
366 18                  170000
367  3                   50000
368 14                  150000
369 16                  160000
370  4                   60000
371  8                   85000
372 19                  170000
373  2                   40000
374  7                   90000
375 15                  150000

  Age Gender Education.Level Job.Title         Years.of.Experience Salary
1 32  Male   Bachelor's      Software Engineer  5                   90000
2 28  Female Master's        Data Analyst       3                   65000
3 45  Male   PhD             Senior Manager    15                  150000
4 36  Female Bachelor's      Sales Associate    7                   60000
5 52  Male   Master's        Director          20                  200000
6 29  Male   Bachelor's      Marketing Analyst  2                   55000

    Age Gender Education.Level Job.Title
370 33  Male   Bachelor's      Junior Business Analyst
371 35  Female Bachelor's      Senior Marketing Analyst
372 43  Male   Master's        Director of Operations
373 29  Female Bachelor's      Junior Project Manager
374 34  Male   Bachelor's      Senior Operations Coordinator
375 44  Female PhD             Senior Business Analyst
    Years.of.Experience Salary
370  4                   60000
371  8                   85000
372 19                  170000
373  2                   40000
374  7                   90000
375 15                  150000

'data.frame':	375 obs. of  6 variables:
 $ Age                : num  32 28 45 36 52 29 42 31 26 38 ...
 $ Gender             : chr  "Male" "Female" "Male" "Female" ...
 $ Education.Level    : chr  "Bachelor's" "Master's" "PhD" "Bachelor's" ...
 $ Job.Title          : chr  "Software Engineer" "Data Analyst" "Senior Manager" "Sales Associate" ...
 $ Years.of.Experience: num  5 3 15 7 20 2 12 4 1 10 ...
 $ Salary             : num  90000 65000 150000 60000 200000 55000 120000 80000 45000 110000 ...

      Age              Gender     Education.Level     Job.Title
 Min.   :23.00   Length   :375   Length   :375    Length   :375
 1st Qu.:31.00   N.unique :  2   N.unique :  3    N.unique :174
 Median :36.00   N.blank  :  0   N.blank  :  0    N.blank  :  0
 Mean   :37.43   Min.nchar:  4   Min.nchar:  3    Min.nchar:  3
 3rd Qu.:44.00   Max.nchar:  6   Max.nchar: 10    Max.nchar: 37
 Max.   :53.00
 NAs    :2
 Years.of.Experience     Salary
 Min.   : 0.00       Min.   :   350
 1st Qu.: 4.00       1st Qu.: 55000
 Median : 9.00       Median : 95000
 Mean   :10.03       Mean   :100577
 3rd Qu.:15.00       3rd Qu.:140000
 Max.   :25.00       Max.   :250000
 NAs    :2           NAs    :2

[1] 375

[1] 6

[1] 375   6

[1] "Age"                 "Gender"              "Education.Level"
[4] "Job.Title"           "Years.of.Experience" "Salary"

  [1] "1"   "2"   "3"   "4"   "5"   "6"   "7"   "8"   "9"   "10"  "11"  "12"
 [13] "13"  "14"  "15"  "16"  "17"  "18"  "19"  "20"  "21"  "22"  "23"  "24"
 [25] "25"  "26"  "27"  "28"  "29"  "30"  "31"  "32"  "33"  "34"  "35"  "36"
 [37] "37"  "38"  "39"  "40"  "41"  "42"  "43"  "44"  "45"  "46"  "47"  "48"
 [49] "49"  "50"  "51"  "52"  "53"  "54"  "55"  "56"  "57"  "58"  "59"  "60"
 [61] "61"  "62"  "63"  "64"  "65"  "66"  "67"  "68"  "69"  "70"  "71"  "72"
 [73] "73"  "74"  "75"  "76"  "77"  "78"  "79"  "80"  "81"  "82"  "83"  "84"
 [85] "85"  "86"  "87"  "88"  "89"  "90"  "91"  "92"  "93"  "94"  "95"  "96"
 [97] "97"  "98"  "99"  "100" "101" "102" "103" "104" "105" "106" "107" "108"
[109] "109" "110" "111" "112" "113" "114" "115" "116" "117" "118" "119" "120"
[121] "121" "122" "123" "124" "125" "126" "127" "128" "129" "130" "131" "132"
[133] "133" "134" "135" "136" "137" "138" "139" "140" "141" "142" "143" "144"
[145] "145" "146" "147" "148" "149" "150" "151" "152" "153" "154" "155" "156"
[157] "157" "158" "159" "160" "161" "162" "163" "164" "165" "166" "167" "168"
[169] "169" "170" "171" "172" "173" "174" "175" "176" "177" "178" "179" "180"
[181] "181" "182" "183" "184" "185" "186" "187" "188" "189" "190" "191" "192"
[193] "193" "194" "195" "196" "197" "198" "199" "200" "201" "202" "203" "204"
[205] "205" "206" "207" "208" "209" "210" "211" "212" "213" "214" "215" "216"
[217] "217" "218" "219" "220" "221" "222" "223" "224" "225" "226" "227" "228"
[229] "229" "230" "231" "232" "233" "234" "235" "236" "237" "238" "239" "240"
[241] "241" "242" "243" "244" "245" "246" "247" "248" "249" "250" "251" "252"
[253] "253" "254" "255" "256" "257" "258" "259" "260" "261" "262" "263" "264"
[265] "265" "266" "267" "268" "269" "270" "271" "272" "273" "274" "275" "276"
[277] "277" "278" "279" "280" "281" "282" "283" "284" "285" "286" "287" "288"
[289] "289" "290" "291" "292" "293" "294" "295" "296" "297" "298" "299" "300"
[301] "301" "302" "303" "304" "305" "306" "307" "308" "309" "310" "311" "312"
[313] "313" "314" "315" "316" "317" "318" "319" "320" "321" "322" "323" "324"
[325] "325" "326" "327" "328" "329" "330" "331" "332" "333" "334" "335" "336"
[337] "337" "338" "339" "340" "341" "342" "343" "344" "345" "346" "347" "348"
[349] "349" "350" "351" "352" "353" "354" "355" "356" "357" "358" "359" "360"
[361] "361" "362" "363" "364" "365" "366" "367" "368" "369" "370" "371" "372"
[373] "373" "374" "375"

[1] "Age"                 "Gender"              "Education.Level"
[4] "Job.Title"           "Years.of.Experience" "Salary"

In [5]:

employee[1,]

employee[2,3]

employee[,3]

employee[1:5,]

  Age Gender Education.Level Job.Title         Years.of.Experience Salary
1 32  Male   Bachelor's      Software Engineer 5                   90000

[1] "Master's"

  [1] "Bachelor's" "Master's"   "PhD"        "Bachelor's" "Master's"
  [6] "Bachelor's" "Master's"   "Bachelor's" "Bachelor's" "PhD"
 [11] "Master's"   "Bachelor's" "Bachelor's" "Master's"   "Bachelor's"
 [16] "Bachelor's" "Master's"   "PhD"        "Bachelor's" "Bachelor's"
 [21] "Master's"   "Master's"   "Bachelor's" "Bachelor's" "Master's"
 [26] "Bachelor's" "Master's"   "Bachelor's" "PhD"        "Master's"
 [31] "Bachelor's" "Bachelor's" "Master's"   "Bachelor's" "PhD"
 [36] "Bachelor's" "Bachelor's" "Master's"   "Bachelor's" "Bachelor's"
 [41] "Master's"   "Master's"   "Bachelor's" "Bachelor's" "Master's"
 [46] "Bachelor's" "Bachelor's" "Master's"   "PhD"        "Bachelor's"
 [51] "Bachelor's" "Master's"   "Bachelor's" "Master's"   "Bachelor's"
 [56] "Bachelor's" "Master's"   "PhD"        "Bachelor's" "Master's"
 [61] "Master's"   "Bachelor's" "Bachelor's" "PhD"        "Bachelor's"
 [66] "Master's"   "Bachelor's" "Bachelor's" "Master's"   "Master's"
 [71] "Bachelor's" "Bachelor's" "PhD"        "Bachelor's" "Master's"
 [76] "Bachelor's" "Bachelor's" "Master's"   "Master's"   "Bachelor's"
 [81] "Bachelor's" "Master's"   "Bachelor's" "PhD"        "Bachelor's"
 [86] "Master's"   "Bachelor's" "Bachelor's" "Master's"   "Bachelor's"
 [91] "PhD"        "Bachelor's" "Bachelor's" "Master's"   "Bachelor's"
 [96] "Bachelor's" "PhD"        "Bachelor's" "Master's"   "Bachelor's"
[101] "Bachelor's" "Master's"   "Master's"   "Bachelor's" "Master's"
[106] "PhD"        "Bachelor's" "Bachelor's" "Master's"   "Bachelor's"
[111] "Master's"   "Bachelor's" "Bachelor's" "Master's"   "Bachelor's"
[116] "Master's"   "Bachelor's" "PhD"        "Bachelor's" "Master's"
[121] "Bachelor's" "Master's"   "Bachelor's" "Bachelor's" "PhD"
[126] "Bachelor's" "Master's"   "Bachelor's" "Bachelor's" "Master's"
[131] "Master's"   "Bachelor's" "Master's"   "PhD"        "Bachelor's"
[136] "Bachelor's" "Master's"   "Bachelor's" "Bachelor's" "Master's"
[141] "Bachelor's" "Master's"   "Bachelor's" "Bachelor's" "Master's"
[146] "Bachelor's" "PhD"        "Bachelor's" "Bachelor's" "Master's"
[151] "Bachelor's" "Master's"   "PhD"        "Bachelor's" "Master's"
[156] "Bachelor's" "Bachelor's" "Master's"   "PhD"        "Bachelor's"
[161] "Bachelor's" "Master's"   "Bachelor's" "Bachelor's" "Master's"
[166] "Bachelor's" "Bachelor's" "PhD"        "Bachelor's" "Master's"
[171] "Master's"   "Bachelor's" "Bachelor's" "Bachelor's" "Master's"
[176] "Bachelor's" "PhD"        "Bachelor's" "Bachelor's" "Master's"
[181] "Bachelor's" "Master's"   "PhD"        "Bachelor's" "Bachelor's"
[186] "Bachelor's" "Master's"   "Bachelor's" "PhD"        "Bachelor's"
[191] "Bachelor's" "Master's"   "Bachelor's" "Bachelor's" "Master's"
[196] "Bachelor's" "Bachelor's" "PhD"        "Bachelor's" "Master's"
[201] "Master's"   "Bachelor's" "Bachelor's" "Master's"   "Bachelor's"
[206] "PhD"        "Bachelor's" "Bachelor's" "Master's"   "Bachelor's"
[211] "Master's"   "PhD"        "Bachelor's" "Bachelor's" "Bachelor's"
[216] "Master's"   "Bachelor's" "PhD"        "Bachelor's" "Bachelor's"
[221] "Master's"   "Bachelor's" "Bachelor's" "Master's"   "Bachelor's"
[226] "Bachelor's" "PhD"        "Bachelor's" "Master's"   "Master's"
[231] "Bachelor's" "Bachelor's" "Master's"   "Bachelor's" "PhD"
[236] "Bachelor's" "Bachelor's" "Master's"   "Bachelor's" "Bachelor's"
[241] "PhD"        "Bachelor's" "Bachelor's" "PhD"        "Bachelor's"
[246] "Bachelor's" "Master's"   "Bachelor's" "Bachelor's" "Master's"
[251] "Bachelor's" "Master's"   "PhD"        "Bachelor's" "Bachelor's"
[256] "Bachelor's" "Master's"   "Bachelor's" "PhD"        "Bachelor's"
[261] "Bachelor's" "Bachelor's" "PhD"        "Bachelor's" "Bachelor's"
[266] "Bachelor's" "Bachelor's" "Master's"   "Bachelor's" "Bachelor's"
[271] "PhD"        "Bachelor's" "Bachelor's" "Master's"   "Bachelor's"
[276] "Bachelor's" "PhD"        "Bachelor's" "Bachelor's" "Master's"
[281] "Bachelor's" "Bachelor's" "Master's"   "Bachelor's" "Bachelor's"
[286] "PhD"        "Bachelor's" "Bachelor's" "Bachelor's" "Bachelor's"
[291] "Bachelor's" "PhD"        "Bachelor's" "Bachelor's" "Master's"
[296] "Bachelor's" "Bachelor's" "PhD"        "Bachelor's" "Bachelor's"
[301] "Master's"   "Bachelor's" "Bachelor's" "PhD"        "Bachelor's"
[306] "Bachelor's" "Master's"   "Bachelor's" "Bachelor's" "Master's"
[311] "Bachelor's" "Bachelor's" "PhD"        "Bachelor's" "Bachelor's"
[316] "Bachelor's" "Master's"   "Bachelor's" "Bachelor's" "Bachelor's"
[321] "Master's"   "Bachelor's" "Bachelor's" "PhD"        "Bachelor's"
[326] "Bachelor's" "PhD"        "Bachelor's" "Bachelor's" "Master's"
[331] "Bachelor's" "Bachelor's" "PhD"        "Bachelor's" "Bachelor's"
[336] "Master's"   "Bachelor's" "Bachelor's" "PhD"        "Bachelor's"
[341] "Bachelor's" "Master's"   "Bachelor's" "Bachelor's" "PhD"
[346] "Bachelor's" "Bachelor's" "Master's"   "Bachelor's" "Bachelor's"
[351] "PhD"        "Bachelor's" "Bachelor's" "Master's"   "Bachelor's"
[356] "Bachelor's" "PhD"        "Bachelor's" "Bachelor's" "Master's"
[361] "Bachelor's" "Bachelor's" "PhD"        "Bachelor's" "Bachelor's"
[366] "Master's"   "Bachelor's" "Bachelor's" "PhD"        "Bachelor's"
[371] "Bachelor's" "Master's"   "Bachelor's" "Bachelor's" "PhD"

  Age Gender Education.Level Job.Title         Years.of.Experience Salary
1 32  Male   Bachelor's      Software Engineer  5                   90000
2 28  Female Master's        Data Analyst       3                   65000
3 45  Male   PhD             Senior Manager    15                  150000
4 36  Female Bachelor's      Sales Associate    7                   60000
5 52  Male   Master's        Director          20                  200000

In [6]:
colnames(employee)

[1] "Age"                 "Gender"              "Education.Level"
[4] "Job.Title"           "Years.of.Experience" "Salary"